# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ruby_robot.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "RubyRobot.RubyRobotRequest" do
    optional :x, :int32, 1
    optional :y, :int32, 2
    optional :direction, :enum, 3, "RubyRobot.RubyRobotRequest.Direction"
  end
  add_enum "RubyRobot.RubyRobotRequest.Direction" do
    value :NORTH, 0
    value :EAST, 1
    value :SOUTH, 2
    value :WEST, 3
  end
  add_message "RubyRobot.RubyRobotError" do
    optional :error, :int32, 1
    optional :message, :string, 2
  end
  add_message "RubyRobot.RubyRobotResponse" do
    oneof :response do
      optional :current_state, :message, 1, "RubyRobot.RubyRobotRequest"
      optional :error, :message, 2, "RubyRobot.RubyRobotError"
    end
  end
end

module RubyRobot
  RubyRobotRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("RubyRobot.RubyRobotRequest").msgclass
  RubyRobotRequest::Direction = Google::Protobuf::DescriptorPool.generated_pool.lookup("RubyRobot.RubyRobotRequest.Direction").enummodule
  RubyRobotError = Google::Protobuf::DescriptorPool.generated_pool.lookup("RubyRobot.RubyRobotError").msgclass
  RubyRobotResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("RubyRobot.RubyRobotResponse").msgclass
end
