#!/usr/bin/env ruby

$:.unshift(File.dirname(__FILE__) + '/../lib') unless $:.include?(File.dirname(__FILE__) + '/../lib')

require 'rubygems'
require 'bundler/setup'
require 'ruby_robot'
require 'uri'
require 'optparse'

#
# TODO: use getoptlong (or optparse) to parse args, including support for --help.
#
if ARGV.size == 1
  uri, *rest = ARGV

  STDOUT.puts "Welcome to the shell; press 'tab' to see available commands"
  STDOUT.puts "(tab-complete is also enabled)"

  if uri.strip.downcase == 'standalone'
    ::Bombshell.launch(::RubyRobot::Shell)
  else
    ::RubyRobot::GrpcShell.remote_url = URI.parse(ARGV.first)
    ::Bombshell.launch(::RubyRobot::GrpcShell)
  end
elsif ARGV.empty?
  ::Bombshell.launch(::RubyRobot::Shell)
else
  STDERR.puts "                  Usage: #{$0} [gRPC_Remote_URL|standalone]"
  STDERR.puts "     Standalone Example: #{$0} standalone"
  STDERR.puts " gRPC Localhost Example: #{$0} grpc://127.0.0.1:31310"
  STDERR.puts "gRPC Remote TLS Example: #{$0} grpcs://netflix.avilla.net:31310"
  exit 1
end
