#!/usr/bin/env ruby

$:.unshift(File.dirname(__FILE__) + '/../lib') unless $:.include?(File.dirname(__FILE__) + '/../lib')

require 'rubygems'
require 'bundler/setup'
$: << File.dirname(__FILE__) + '/../lib/ruby_robot/grpc_ruby'
require 'ruby_robot/grpc/ruby_robot_services_pb'
require 'ruby_robot'
require 'json'

def main
  stub = ::RubyRobot::RubyRobot::Stub.new('localhost:31310', :this_channel_is_insecure)
  stub.remove(Google::Protobuf::Empty.new)
  puts stub.left(  Google::Protobuf::Empty.new).error.message
  puts stub.move(  Google::Protobuf::Empty.new).error.message
  puts stub.remove(Google::Protobuf::Empty.new)
  puts stub.report(Google::Protobuf::Empty.new).error.message
  puts stub.right( Google::Protobuf::Empty.new).error.message

  # Replicate tests from original spec: PLACE 0,0,NORTH; MOVE; REPORT
  stub.remove(Google::Protobuf::Empty.new)
  cs = stub.place(::RubyRobot::RubyRobotRequest.new(x: 0, y: 0, direction: :NORTH)).current_state
  stub.move(Google::Protobuf::Empty.new)
  puts stub.report(Google::Protobuf::Empty.new).current_state.to_json

  # PLACE 0,0,NORTH; LEFT; REPORT
  stub.remove(Google::Protobuf::Empty.new)
  cs = stub.place(::RubyRobot::RubyRobotRequest.new(x: 0, y: 0, direction: :NORTH)).current_state
  stub.left(Google::Protobuf::Empty.new)
  puts stub.report(Google::Protobuf::Empty.new).current_state.to_json

  # PLACE 1,2,EAST; MOVE; MOVE; LEFT; MOVE; REPORT
  stub.remove(Google::Protobuf::Empty.new)
  cs = stub.place(::RubyRobot::RubyRobotRequest.new(x: 1, y: 2, direction: :EAST)).current_state
  stub.move(Google::Protobuf::Empty.new)
  stub.move(Google::Protobuf::Empty.new)
  stub.left(Google::Protobuf::Empty.new)
  stub.move(Google::Protobuf::Empty.new)
  puts stub.report(Google::Protobuf::Empty.new).current_state.to_json

  # PLACE 1,2,EAST; MOVE; MOVE; LEFT; MOVE; PLACE 100,1,SOUTH; REPORT
  stub.remove(Google::Protobuf::Empty.new)
  cs = stub.place(::RubyRobot::RubyRobotRequest.new(x: 1, y: 2, direction: :EAST)).current_state
  stub.move(Google::Protobuf::Empty.new)
  stub.move(Google::Protobuf::Empty.new)
  stub.left(Google::Protobuf::Empty.new)
  stub.move(Google::Protobuf::Empty.new)
  puts stub.place(::RubyRobot::RubyRobotRequest.new(x: 100, y: 1, direction: :SOUTH)).current_state
  puts stub.report(Google::Protobuf::Empty.new).current_state.to_json
end

main
